## Introduction to NumPy

In [1]:
import numpy as np
np.version.version

'2.4.6'

In [2]:
vector_a=np.array([[[1,2,3]]],dtype='float64')
vector_a


array([[[1., 2., 3.]]])

In [3]:
vector_a.dtype

dtype('float64')

In [4]:
vector_a.shape

(1, 1, 3)

In [5]:
vector_a.size

3

In [6]:
vector_b=np.array([1,2,3,'a'])
vector_b

array(['1', '2', '3', 'a'], dtype='<U21')

In [7]:
vector_b.dtype

dtype('<U21')

### Multidimensional array

In [8]:
multi_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
multi_a.shape

(3, 3)

In [10]:
multi_a.size # RETURN THE TOTAL NO OF ELEMENT

9

In [11]:
multi_a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
help(multi_a)

Help on ndarray:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
    ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
    --

    ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

    An array object represents a multidimensional, homogeneous array
    of fixed-size items.  An associated data-type object describes the
    format of each element in the array (its byte-order, how many bytes it
    occupies in memory, whether it is an integer, a floating point number,
    or something else, etc.)

    Arrays should be constructed using `array`, `zeros` or `empty` (refer
    to the See Also section below).  The parameters given here refer to
    a low-level method (`ndarray(...)`) for instantiating an array.

    For more information, refer to the `numpy` module and examine the
    methods and attributes of an array.

    Parameters
    ----------
    (for the __new__ method; see Notes below)

    shape : tuple of ints
        

#### The array without proper shape cannot be made
#### Eg:

In [13]:
multi_b=np.array([[1,2,3],[4,6],[7,8,9]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

#### We can define the dimension

In [ ]:
vector_c=np.array([1,2,3,],ndmin=5)
vector_c.shape


(1, 1, 1, 1, 3)

#### Creating arrays with Arange

- It is same as the range() function of the python

In [ ]:
arange_a=np.arange(20)
arange_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arange_a=np.arange(2,20,2)
arange_a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Creating arrays of ones, zero and empty

In [ ]:
ones_a=np.ones((3),dtype='int64')
ones_a

array([1, 1, 1])

In [ ]:
ones_b=np.ones((3,4),dtype='int64')
ones_b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
zero_a=np.zeros((4,5))
zero_a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
mat=np.ones((6,7)) *3
mat

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

### Accessing and slicing Numpy Arrays

In [16]:
mat[-3]

array([3., 3., 3., 3., 3., 3., 3.])

In [15]:
mat[1:5]

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

#### Boolean indexing

In [23]:
bool_a=np.array([[1,2],[3,4],[5,6]],)
bool_indx=(bool_a>2)
bool_indx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [24]:
bool_a[bool_indx]

array([3, 4, 5, 6])

In [41]:
bool_b=np.array(['python','java','ruby','rust'])
bool_indx=((bool_b == 'python') & (bool_b == 'ruby'))
bool_indx

array([False, False, False, False])

In [42]:
a=np.arange(40)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

#### Matrix addition and subtraction

In [ ]:
## single element -1 is added to all the each element of the x
x=np.array([1,2,3])
y=np.array([-1])
output=np.add(x,y)
output

array([0, 1, 2])

In [51]:
## This approache is not possible because of the shape conflict
x=np.array([1,2,3])
y=np.array([-1,2])
output=np.add(x,y)
output

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Statistics and Linear Algebra

In [52]:
## Transpose
x=np.array([[1,2,3,4],[5,6,7,8]])
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
sum_a=x.sum()
sum_a

np.int64(36)

In [55]:
## COLUMN WISE SUM
x.sum(axis=0)

array([ 6,  8, 10, 12])

In [56]:
## ROW WISE SUM
x.sum(axis=1)

array([10, 26])

#### Mean

In [57]:
x.mean()

np.float64(4.5)

In [58]:
x.mean(axis=1)

array([2.5, 6.5])

In [59]:
x.mean(axis=0)

array([3., 4., 5., 6.])

#### Matrix multiplication

In [63]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b=np.array([[2,3,4,5,6],[7,8,9,10,11]])
c=a*b
c

array([[  2,   6,  12,  20,  30],
       [ 42,  56,  72,  90, 110]])